title: "Tech Blog - Balasubramanian S"
description: "ðŸŽ¯ Aspiring Cloud Engineer | DevOps Enthusiast | Continuous Learner"
author: "Balasubramanian S"
remote_theme: pages-themes/architect@v0.2.0
markdown: kramdown

# Social links
github_username: balasubramanian-s
linkedin_username: balasubramanian-s-257354137

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

# Show excerpts on home page
show_excerpts: true
